using UnityEngine;
using UnityEngine.InputSystem;

public class CameraHandler : MonoBehaviour
{
    [SerializeField] private float padding = 15f;
    public static CameraHandler Instance;

    private Camera camera;
    
    //input action references
    [SerializeField] private InputActionReference moveAction;
    [SerializeField] private InputActionReference panAction;
    [SerializeField] private InputActionReference mouseMovementAction;
    [SerializeField] private InputActionReference zoomAction;
    [SerializeField] private InputActionReference pieceMovementAction;

    private GameObject selectedPiece;
    private Vector3 dragOffset;

    private void Awake()
    {
        //helps prevent the possibility of having two competing instances of this class
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
            return;
        }

        Instance = this;

        camera = GetComponent<Camera>();
    }

    private void OnEnable()
    {
        moveAction.action.Enable();
        panAction.action.Enable();
        mouseMovementAction.action.Enable();
        zoomAction.action.Enable();
        pieceMovementAction.action.Enable();
    }

    private void OnDisable()
    {
        moveAction.action.Disable();
        panAction.action.Disable();
        mouseMovementAction.action.Disable();
        zoomAction.action.Disable();
        pieceMovementAction.action.Disable();
    }

    //generated by AI
    //functions to automatically adjust the camera position to fit the puzzle board
    public void FrameBoard(float boardWidth, float boardHeight)
    {
        float verticalSize = boardHeight / 2f;

        float horizontalSize = boardWidth / (2f * camera.aspect);

        float requiredSize = Mathf.Max(
            verticalSize,
            horizontalSize
        );

        camera.orthographicSize = requiredSize + padding;

        camera.transform.position = new Vector3(
            0,
            0,
            camera.transform.position.z
        );
    }

    //handles the wasd camera movement, panning, and zooming
    private void HandleMovement()
    {
        float moveSpeed = 50f;
        Vector2 input = moveAction.action.ReadValue<Vector2>();

        Vector3 movement =
            new Vector3(input.x, input.y, 0f)
            * moveSpeed
            * Time.deltaTime;
        camera.transform.position += movement;
    }
    private void HandlePan()
    {
        float panSpeed = 0.1f;
        if (panAction.action.IsPressed())
        {
            Vector2 mouseDelta = mouseMovementAction.action.ReadValue<Vector2>();
            Vector3 panMovement = new Vector3(-mouseDelta.x, -mouseDelta.y, 0f) * panSpeed;
            camera.transform.position += panMovement;
        }
    }
    private void HandleZoom()
    {
        float zoomSpeed = 5f;
        float zoom = zoomAction.action.ReadValue<Vector2>().y;

        camera.orthographicSize -= zoom * zoomSpeed;
        camera.orthographicSize = Mathf.Clamp(camera.orthographicSize, 1f, 100f);
    }

    private void HandlePieceDragging()
    {
        if (pieceMovementAction.action.WasPressedThisFrame())
        {
            Vector3 mouseScreenPosition = Mouse.current.position.ReadValue();
            Vector3 mouseWorldPosition = Camera.main.ScreenToWorldPoint(mouseScreenPosition);
            mouseWorldPosition.z = 0f; // Set z to 0 to ensure the piece stays in the correct plane
            Collider2D hit = Physics2D.OverlapPoint(mouseWorldPosition);
            if (hit == null)
            {
                return;
            }
            selectedPiece = hit.gameObject;
            dragOffset = selectedPiece.transform.position - mouseWorldPosition;
        }
        // Check if the left mouse button is pressed
        if (pieceMovementAction.action.IsPressed() && selectedPiece != null)
        {
            Vector3 mouseScreenPosition = Mouse.current.position.ReadValue();
            Vector3 mouseWorldPosition = Camera.main.ScreenToWorldPoint(mouseScreenPosition);
            mouseWorldPosition.z = 0f; // Set z to 0 to ensure the piece stays in the correct plane
            selectedPiece.transform.position = mouseWorldPosition + dragOffset;
        }
        if (pieceMovementAction.action.WasReleasedThisFrame())
        {
            //snap piece functionality
            selectedPiece = null;
        }
    }

    void Update()
    {
        HandleMovement();
        HandlePan();
        HandleZoom();
        HandlePieceDragging();
    }
}
