using UnityEngine;

public class CameraHandler : MonoBehaviour
{
    [SerializeField] private float padding = 15f;
    public static CameraHandler Instance;
    
    private void Awake()
    {
        //helps prevent the possibility of having two competing instances of this class
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
            return;
        }

        Instance = this;
    }

    //generated by AI
    //functions to automatically adjust the camera position to fit the puzzle board
    public void FrameBoard(float boardWidth, float boardHeight)
    {
        Camera camera = GetComponent<Camera>();

        float verticalSize = boardHeight / 2f;

        float horizontalSize = boardWidth / (2f * camera.aspect);

        float requiredSize = Mathf.Max(
            verticalSize,
            horizontalSize
        );

        camera.orthographicSize = requiredSize + padding;

        camera.transform.position = new Vector3(
            0,
            0,
            camera.transform.position.z
        );
    }
}
