using UnityEngine;
using UnityEngine.InputSystem;

public class CameraHandler : MonoBehaviour
{
    [SerializeField] private float padding = 15f;
    public static CameraHandler Instance;

    private Camera camera;
    
    //input action references
    [SerializeField] private InputActionReference moveAction;
    [SerializeField] private InputActionReference panAction;
    [SerializeField] private InputActionReference mouseMovementAction;
    [SerializeField] private InputActionReference zoomAction;
    [SerializeField] private InputActionReference pieceMovementAction;

    private GameObject selectedPiece;
    private Vector3 dragOffset;

    private void Awake()
    {
        //helps prevent the possibility of having two competing instances of this class
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
            return;
        }

        Instance = this;

        camera = GetComponent<Camera>();
    }

    private void OnEnable()
    {
        moveAction.action.Enable();
        panAction.action.Enable();
        mouseMovementAction.action.Enable();
        zoomAction.action.Enable();
        pieceMovementAction.action.Enable();
    }

    private void OnDisable()
    {
        moveAction.action.Disable();
        panAction.action.Disable();
        mouseMovementAction.action.Disable();
        zoomAction.action.Disable();
        pieceMovementAction.action.Disable();
    }

    //generated by AI
    //functions to automatically adjust the camera position to fit the puzzle board
    public void FrameBoard(float boardWidth, float boardHeight)
    {
        float verticalSize = boardHeight / 2f;

        float horizontalSize = boardWidth / (2f * camera.aspect);

        float requiredSize = Mathf.Max(
            verticalSize,
            horizontalSize
        );

        camera.orthographicSize = requiredSize + padding;

        camera.transform.position = new Vector3(
            0,
            0,
            camera.transform.position.z
        );
    }

    //handles the wasd camera movement, panning, and zooming
    private void HandleMovement()
    {
        float moveSpeed = camera.orthographicSize;
        Vector2 input = moveAction.action.ReadValue<Vector2>();

        Vector3 movement =
            new Vector3(input.x, input.y, 0f)
            * moveSpeed
            * Time.deltaTime;
        camera.transform.position += movement;
    }
    private void HandlePan()
    {
        float panSpeed = camera.orthographicSize * 0.005f;
        if (panAction.action.IsPressed())
        {
            Vector2 mouseDelta = mouseMovementAction.action.ReadValue<Vector2>();
            Vector3 panMovement = new Vector3(-mouseDelta.x, -mouseDelta.y, 0f) * panSpeed;
            camera.transform.position += panMovement;
        }
    }
    private void HandleZoom()
    {
        float zoomSpeed = camera.orthographicSize * 0.1f;
        float zoom = zoomAction.action.ReadValue<Vector2>().y;

        camera.orthographicSize -= zoom * zoomSpeed;
        camera.orthographicSize = Mathf.Clamp(camera.orthographicSize, 1f, 100000f);
    }

    private void HandlePieceDragging()
    {
        if (PuzzleUIHandler.isDragging || PuzzleUIHandler.isPointerOverPopup) return;
        if (pieceMovementAction.action.WasPressedThisFrame())
        {
            Vector3 mouseScreenPosition = Mouse.current.position.ReadValue();
            Vector3 mouseWorldPosition = Camera.main.ScreenToWorldPoint(mouseScreenPosition);
            mouseWorldPosition.z = 0f; // Set z to 0 to ensure the piece stays in the correct plane
            if (Physics2D.OverlapPoint(mouseWorldPosition) == null)
            {
                return;
            }
            Collider2D hit = Physics2D.OverlapPoint(mouseWorldPosition);
            selectedPiece = hit.gameObject;
            dragOffset = selectedPiece.transform.position - mouseWorldPosition;
            dragOffset.z = -1f; // Set z to -1 to ensure the piece stays above all other pieces while being dragged
            PuzzlePiece puzzlePiece = selectedPiece.GetComponent<PuzzlePiece>();
            if (puzzlePiece.currentGridPosition.x != -1 && puzzlePiece.currentGridPosition.y != -1)
            {
                PuzzleManager.occupiedGridPositions[puzzlePiece.currentGridPosition.x, puzzlePiece.currentGridPosition.y] = 0; // Mark the grid position as unoccupied
                puzzlePiece.currentGridPosition = new Vector2Int(-1, -1); // Reset the current grid position
            }
        }
        // Check if the left mouse button is pressed
        if (pieceMovementAction.action.IsPressed() && selectedPiece != null)
        {
            Vector3 mouseScreenPosition = Mouse.current.position.ReadValue();
            Vector3 mouseWorldPosition = Camera.main.ScreenToWorldPoint(mouseScreenPosition);
            mouseWorldPosition.z = 0f; // Set z to 0 to ensure the piece stays in the correct plane
            selectedPiece.transform.position = mouseWorldPosition + dragOffset;
        }
        if (pieceMovementAction.action.WasReleasedThisFrame() && selectedPiece != null)
        {
            //snap piece functionality
            Vector2Int gridPosition = PuzzleManager.GetPieceGridPosition(selectedPiece.transform.position);
            PuzzlePiece puzzlePiece = selectedPiece.GetComponent<PuzzlePiece>();
            if (gridPosition.x != -1 && gridPosition.y != -1)
            {
                if (PuzzleManager.occupiedGridPositions[gridPosition.x, gridPosition.y] == 0)
                {
                    Vector3 snapPosition = PuzzleManager.GetBoardPosition(gridPosition.x, gridPosition.y);
                    snapPosition.z = 0.5f; // Set z to 0.5 to ensure the piece stays below pieces being moved on board
                    selectedPiece.transform.position = snapPosition;
                    puzzlePiece.currentGridPosition = gridPosition;
                    PuzzleManager.occupiedGridPositions[gridPosition.x, gridPosition.y] = 1; // Mark the grid position as occupied
                    PuzzleManager.CheckPuzzleCompletion();
                }
                else
                {
                    puzzlePiece.currentGridPosition = new Vector2Int(-1, -1);
                    Vector3 resetPosition = selectedPiece.transform.position;
                    resetPosition.z = 0f; //set position back to 0 so it is not above new moved pieces
                    selectedPiece.transform.position = resetPosition;
                }
            }
            else
            {
                puzzlePiece.currentGridPosition = new Vector2Int(-1, -1);
                Vector3 resetPosition = selectedPiece.transform.position;
                resetPosition.z = 0f; //set position back to 0 so it is not above new moved pieces
                selectedPiece.transform.position = resetPosition;
            }
            selectedPiece = null;
        }
    }

    void Update()
    {
        HandleMovement();
        HandlePan();
        HandleZoom();
        HandlePieceDragging();
    }
}
